// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using face_recognition_api.Data;

#nullable disable

namespace face_recognition_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610033441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("face_recognition_api.Models.Camera", b =>
                {
                    b.Property<long>("CameraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("face_recognition_api.Models.Credential", b =>
                {
                    b.Property<long>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CredentialId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialId");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("face_recognition_api.Models.Employee", b =>
                {
                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("face_recognition_api.Models.EmployeeRole", b =>
                {
                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeEmpId")
                        .HasColumnType("bigint");

                    b.HasKey("EmpId", "RoleId");

                    b.HasIndex("EmployeeEmpId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("face_recognition_api.Models.FaceEmbedded", b =>
                {
                    b.Property<long>("FaceEmbeddedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FaceEmbeddedId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeEmpId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("FaceEmbeddedData")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("FaceEmbeddedId");

                    b.HasIndex("EmployeeEmpId");

                    b.ToTable("FaceEmbeddeds");
                });

            modelBuilder.Entity("face_recognition_api.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("face_recognition_api.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<long?>("CameraId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmpId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EmployeeEmpId")
                        .HasColumnType("bigint");

                    b.HasKey("TransactionId");

                    b.HasIndex("CameraId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmpId");

                    b.HasIndex("EmployeeEmpId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("face_recognition_api.Models.Credential", b =>
                {
                    b.HasOne("face_recognition_api.Models.Employee", "Employee")
                        .WithOne("Credential")
                        .HasForeignKey("face_recognition_api.Models.Credential", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("face_recognition_api.Models.EmployeeRole", b =>
                {
                    b.HasOne("face_recognition_api.Models.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("face_recognition_api.Models.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("face_recognition_api.Models.FaceEmbedded", b =>
                {
                    b.HasOne("face_recognition_api.Models.Employee", "Employee")
                        .WithMany("FaceEmbeddeds")
                        .HasForeignKey("EmployeeEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("face_recognition_api.Models.Transaction", b =>
                {
                    b.HasOne("face_recognition_api.Models.Camera", "Camera")
                        .WithMany("Transactions")
                        .HasForeignKey("CameraId");

                    b.HasOne("face_recognition_api.Models.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeEmpId");

                    b.Navigation("Camera");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("face_recognition_api.Models.Camera", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("face_recognition_api.Models.Employee", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("FaceEmbeddeds");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("face_recognition_api.Models.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
